saleor/dashboard/widget/banner/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$',
        views.banner_list, name='banner-list'),
    # url(r'^banner/(?P<pk>[0-9]+)/$',
    #     views.banner_details, name='banner-details'),
    url(r'^add/$',
        views.banner_create, name='banner-create'),
    url(r'^(?P<pk>[0-9]+)/edit/$',
        views.banner_edit, name='banner-edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.banner_delete, name='banner-delete'),
]

saleor/dashboard/widget/scene/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # Scenes views -------------------------------------------------------------
    url(r'^$',
        views.scene_list, name='scene-list'),
    url(r'^scene/(?P<pk>[0-9]+)/$',
        views.scene_details, name='scene-details'),
    url(r'^add/$',
        views.scene_create, name='scene-create'),
    url(r'^(?P<pk>[0-9]+)/edit/$',
        views.scene_edit, name='scene-edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.scene_delete, name='scene-delete'),

    # Spotlight views ----------------------------------------------------------
    url(
        r'^(?P<scene_pk>[0-9]+)/spotlight/add/$',
        views.spotlight_create, name='spotlight-create', ),
    url(
        r'^(?P<scene_pk>[0-9]+)/spotlight/(?P<spotlight_pk>[0-9]+)/edit/$',
        views.spotlight_edit, name='spotlight-edit', ),
    url(
        r'^(?P<scene_pk>[0-9]+)/spotlight/(?P<spotlight_pk>[0-9]+)/delete/$',
        views.spotlight_delete, name='spotlight-delete', )
]

saleor/dashboard/widget/slider/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # Sliders views ------------------------------------------------------------
    url(
        r'^$',
        views.slider_list,
        name='slider-list', ),
    url(
        r'^(?P<pk>[0-9]+)/$',
        views.slider_detail,
        name='slider-details', ),
    url(
        r'^add/$',
        views.slider_add,
        name='slider-add', ),
    url(
        r'^(?P<pk>[0-9]+)/edit/$',
        views.slider_edit,
        name='slider-edit', ),
    url(
        r'^(?P<pk>[0-9]+)/delete/$',
        views.slider_delete,
        name='slider-delete', ),

    # Slides views -------------------------------------------------------------
    url(
        r'^(?P<slider_pk>[0-9]+)/slide/add/$',
        views.slide_create,
        name='slide-create', ),
    url(
        r'^(?P<slider_pk>[0-9]+)/slide/(?P<slide_pk>[0-9]+)/edit/$',
        views.slide_edit,
        name='slide-edit', ),
    url(
        r'^(?P<slider_pk>[0-9]+)/slide/(?P<slide_pk>[0-9]+)/delete/$',
        views.slide_delete,
        name='slide-delete', ),
    url(
        r'^(?P<slider_pk>[0-9]+)/slides/reorder/$',
        views.ajax_reorder_slides,
        name='ajax-reorder-slides', ),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .vuefront.urls import urlpatterns as vuefront_urls

# handler404 = 'saleor.core.views.handle_404'
# handler404 = 'saleor.vuefront.views.error.not_found'

non_translatable_urlpatterns = [
    # url(
    #     r'^admin/', admin.site.urls),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql/', csrf_exempt(GraphQLView.as_view(
        schema=schema)), name='api'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/$', set_language, name='set_language'),
    url('', include('social_django.urls', namespace='social'))
]

translatable_urlpatterns = [
    url(r'^saleor', include(core_urls)),
    url(r'^saleor/checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^saleor/jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^saleor/order/', include((order_urls, 'order'), namespace='order')),
    url(r'^saleor/page/', include((page_urls, 'page'), namespace='page')),
    url(r'^saleor/products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^saleor/account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^saleor/feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^saleor/search/', include((search_urls, 'search'), namespace='search'))]

# Handle other routes with index.html
urlpatterns = [
    url(
        r'^api/',
        include(
            'saleor.rest.urls',
            namespace='rest-api'
        )
    ),
    url(
        r'^',
        include(
            (
                vuefront_urls,
                'frontend'
            ),
            namespace='app'
        )
    ),
]

urlpatterns += non_translatable_urlpatterns + \
    i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(
            r'^__debug__/',
            include(debug_toolbar.urls)
        ),
        # url(
        #     r'^static/(?P<path>.*)$',
        #     serve
        # )
    ]

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

    # static files (images, css, javascript, etc.)
    # url(r'^static/(?P<path>.*)$', serve)] + static(
    #     '/media/', document_root = settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))]

saleor/dashboard/widget/banner/forms.py
from django import forms
from django.utils.translation import pgettext_lazy

from ....widget.models import Banner
from ...product.widgets import ImagePreviewWidget


class BannerForm(forms.ModelForm):
    class Meta:
        model = Banner
        fields = [
            'name',
            'image',
            'alt',
            'is_active',
            'active_on',
            'active_until',
            'is_default',
        ]

        labels = {
            'name': pgettext_lazy(
                'Banner field name', 'Name', ),
            'image': pgettext_lazy(
                'Banner field name', 'Image', ),
            'alt': pgettext_lazy(
                'Banner field name', 'Alternative text', ),
            'is_active': pgettext_lazy(
                'Slider active state', 'Is public', ),
            'active_on': pgettext_lazy(
                'Slider active state', 'Public since', ),
            'active_until': pgettext_lazy(
                'active_until', 'Public until', ),
            'is_default': pgettext_lazy(
                'is_default', 'Use as default', ), }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.image:
            self.fields['image'].widget = ImagePreviewWidget()

saleor/dashboard/widget/benefit/forms.py
from django import forms
from django.utils.translation import pgettext_lazy

from ....widget.models import Benefit
from ...product.widgets import ImagePreviewWidget
from ....widget.thumbnails import create_benefit_thumbnails


class BenefitForm(forms.ModelForm):
    class Meta:
        model = Benefit
        fields = [
            'name',
            'text',
            'image',
            'is_active',
        ]

        labels = {
            'name': pgettext_lazy(
                'Benefit field name',
                'Nombre',
            ),
            'text': pgettext_lazy(
                'Benefit field name',
                'Texto',
            ),
            'image': pgettext_lazy(
                'Benefit field name',
                'Imagen',
            ),
            'is_active': pgettext_lazy(
                'Slider active state',
                'Activo',
            ),
        }

    def save(self, commit=True):
        print("*** *** ***")
        print("save benefit from form")
        print("*** *** ***")
        benefit = super().save(commit=commit)
        create_benefit_thumbnails.delay(benefit.pk)
        return benefit

saleor/dashboard/widget/scene/forms.py
from django import forms
from django.utils.translation import pgettext_lazy

from ....widget.models import Scene, Spotlight
from ...product.widgets import ImagePreviewWidget


class SceneForm(forms.ModelForm):
    class Meta:
        model = Scene
        fields = [
            'name',
            'image',
            'alt',
            'is_active',
            'active_on',
            'active_until',
        ]

        labels = {
            'name': pgettext_lazy(
                'Scene field name', 'Name', ),
            'image': pgettext_lazy(
                'Scene field name', 'Image', ),
            'alt': pgettext_lazy(
                'Scene field name', 'Alternative text', ),
            'is_active': pgettext_lazy(
                'Scene active state', 'Is public', ),
            'active_on': pgettext_lazy(
                'Scene active state', 'Public since', ),
            'active_until': pgettext_lazy(
                'active_until', 'Public until', ),
            'is_default': pgettext_lazy(
                'is_default', 'Use as default', ), }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.image:
            self.fields['image'].widget = ImagePreviewWidget()


class SpotlightForm(forms.ModelForm):
    class Meta:
        model = Spotlight
        fields = [
            'scene',
            'point_x',
            'point_y',
            'product', ]
        labels = {
            'scene': pgettext_lazy(
                'Spotlight field name', 'Scene'),
            'point_x': pgettext_lazy(
                'Spotlight field name', 'X'),
            'point_y': pgettext_lazy(
                'Spotlight field name', 'Y'),
            'product': pgettext_lazy(
                'Spotlight field name', 'Featured product'), }
        widgets = {
            'scene': forms.widgets.HiddenInput(), }

saleor/dashboard/widget/banner/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import pgettext_lazy

from ....core.utils import get_paginator_items
from ....widget.models import Banner
from ...views import staff_member_required
from .filters import BannerFilter
from . import forms


@staff_member_required
@permission_required('site.manage_settings')
def banner_list(request):
    banners = Banner.objects.all()
    banner_filter = BannerFilter(request.GET, queryset=banners)
    banners = get_paginator_items(
        banner_filter.qs,
        settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'), )

    ctx = {
        'banners': banners,
        'filter_set': banner_filter,
        'is_empty': not banner_filter.queryset.exists()}

    return TemplateResponse(
        request,
        'dashboard/widget/banner/list.html',
        ctx, )


# @staff_member_required
# @permission_required('site.manage_settings')
# def banner_details(request, pk):
#     banner = get_object_or_404(Banner, pk=pk)
#     ctx = {
#         'banner': banner
#     }
#     return TemplateResponse(
#         request,
#         'dashboard/widget/banner/detail.html',
#         ctx, )


@staff_member_required
@permission_required('site.manage_settings')
def banner_create(request):
    banner = Banner()
    form = forms.BannerForm(
        request.POST or None,
        request.FILES or None,
        instance=banner, )

    if form.is_valid():
        banner = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Nuevo banner añadido'), )

        return redirect('dashboard:banner-list')

    ctx = {
        'banner': banner,
        'form': form, }

    return TemplateResponse(
        request,
        'dashboard/widget/banner/form.html',
        ctx, )


@staff_member_required
@permission_required('site.manage_settings')
def banner_edit(request, pk):
    banner = get_object_or_404(Banner, pk=pk)
    form = forms.BannerForm(
        request.POST or None,
        request.FILES or None,
        instance=banner, )
    if form.is_valid():
        banner = form.save()
        msg = pgettext_lazy('Dashboard message', 'Banner actualizado')
        messages.success(request, msg)
        return redirect('dashboard:banner-list')
    ctx = {
        'banner': banner,
        'form': form
    }

    return TemplateResponse(
        request,
        'dashboard/widget/banner/form.html',
        ctx, )


@staff_member_required
@permission_required('site.manage_settings')
def banner_delete(request, pk):
    banner = get_object_or_404(Banner, pk=pk)
    if request.method == 'POST':
        banner.delete()
        msg = pgettext_lazy(
            'Dashboard message',
            'Banner eliminado %s') % (banner.name,)
        messages.success(
            request,
            msg, )
        return redirect('dashboard:banner-list')

    ctx = {
        'banner': banner, }
    return TemplateResponse(
        request,
        'dashboard/widget/banner/modal/confirm_delete.html',
        ctx
    )

saleor/dashboard/widget/benefit/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import pgettext_lazy

from ....core.utils import get_paginator_items
from ....widget.models import Benefit
from ...views import staff_member_required
from .filters import BenefitFilter
from . import forms


@staff_member_required
@permission_required('site.manage_settings')
def benefit_list(request):
    benefits = Benefit.objects.all()
    benefit_filter = BenefitFilter(request.GET, queryset=benefits)
    benefits = get_paginator_items(
        benefit_filter.qs,
        settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'), )

    ctx = {
        'benefits': benefits,
        'filter_set': benefit_filter,
        'is_empty': not benefit_filter.queryset.exists()}

    return TemplateResponse(
        request,
        'dashboard/widget/benefit/list.html',
        ctx, )


@staff_member_required
@permission_required('site.manage_settings')
def benefit_create(request):
    benefit = Benefit()
    form = forms.BenefitForm(
        request.POST or None,
        request.FILES or None,
        instance=benefit, )

    if form.is_valid():
        benefit = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Nuevo benefit añadido'), )

        return redirect('dashboard:benefit-list')

    ctx = {
        'benefit': benefit,
        'form': form, }

    return TemplateResponse(
        request,
        'dashboard/widget/benefit/form.html',
        ctx, )


@staff_member_required
@permission_required('site.manage_settings')
def benefit_edit(request, pk):
    benefit = get_object_or_404(Benefit, pk=pk)
    form = forms.BenefitForm(
        request.POST or None,
        request.FILES or None,
        instance=benefit, )
    if form.is_valid():
        benefit = form.save()
        msg = pgettext_lazy('Dashboard message', 'Benefit actualizado')
        messages.success(request, msg)
        return redirect('dashboard:benefit-list')
    ctx = {
        'benefit': benefit,
        'form': form
    }

    return TemplateResponse(
        request,
        'dashboard/widget/benefit/form.html',
        ctx, )


@staff_member_required
@permission_required('site.manage_settings')
def benefit_delete(request, pk):
    benefit = get_object_or_404(Benefit, pk=pk)
    if request.method == 'POST':
        benefit.delete()
        msg = pgettext_lazy(
            'Dashboard message',
            'Benefit eliminado %s') % (benefit.name,)
        messages.success(
            request,
            msg, )
        return redirect('dashboard:benefit-list')

    ctx = {
        'benefit': benefit, }
    return TemplateResponse(
        request,
        'dashboard/widget/benefit/modal/confirm_delete.html',
        ctx
    )

saleor/widget/views.py
from django.shortcuts import render

# Create your views here.

templates/dashboard/widget/scene/detail.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load mptt_tags %}
{% load materializecss %}
{% load static %}
{% load utils %}

{% block title %}
  {% trans "Scene" context "Scene detail page title" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-scenes{% endblock %}

{% block menu_content_management_header_class %}active{% endblock %}
{% block menu_scene_class %}active{% endblock %}

{% block header_menu %}
  {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li class="visible-s">
      <span>
        {% trans "Banners" context "Dashboard scenes list" %}
      </span>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:scene-list' %}">
        <svg data-src="{% static 'dashboard/images/arrow-left.svg' %}" fill="#fff" width="20px" height="20px" ></svg>
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {{ scene }}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row scenes">
    <div class="col s12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ scene.name }}
          </span>
          <div class="row">
            <div class="col s12">
              <input id="id_default" name="default" class="filled-in green" type="checkbox" {% if scene.is_active %}checked="checked"{% endif %}>
              <label for="id_default" style="pointer-events:none;">
                {% trans "Active" context "Slider list table header is active" %}
              </label>
            </div>
          </div>
        </div>
        <div class="card-action">
          <a class="btn-flat waves-effect" href="{% url 'dashboard:scene-edit' pk=scene.pk %}">
            {% trans "Editar" context "Category detail view action" %}
          </a>
          <a href="#base-modal" class="btn-flat waves-effect modal-trigger-custom" data-href="{% url 'dashboard:scene-delete' pk=scene.pk %}">
            {% trans "Eliminar" context "Category detail view action" %}
          </a>
        </div>
      </div>
    </div>


    <div class="col s12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{% trans "Spotlights" %}</span>
        </div>

        <div class="data-table-header-action">
          <a href="{% url 'dashboard:spotlight-create' scene_pk=scene.pk %}" class="btn-flat waves-effect">
            {% trans "Add" %}
          </a>
        </div>
        <div class="data-table-container">
          <table class="bordered highlight responsive data-table">
            <thead>
              <tr>
                <th>{% trans "Product" %}</th>
                <th>{% trans "X" %}</th>
                <th>{% trans "Y" %}</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for spotlight in scene.spotlights.all %}
                <tr>
                  <td>
                    {{ spotlight.product }}
                  </td>
                  <td>
                    {{ spotlight.point_x }}%
                  </td>
                  <td>
                    {{ spotlight.point_y }}%
                  </td>
                  <td class="right-align">
                    <a href="{% url 'dashboard:spotlight-edit' scene_pk=scene.pk spotlight_pk=spotlight.pk %}" class="btn-flat waves-effect">
                      {% trans 'Edit' context 'Attribute value edit action' %}
                    </a>
                    <a class="btn-flat waves-effect modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:spotlight-delete' scene_pk=scene.pk spotlight_pk=spotlight.pk  %}">
                      {% trans 'Remove' context 'Attribute value edit action' %}
                    </a>
                  </td>
                </tr>
              {% empty %}
                <tr>
                  <td colspan="2">{% trans "No has creado spotlights para este scene" context "Empty list of attribute values" %}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

templates/dashboard/widget/scene/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load mptt_tags %}
{% load materializecss %}
{% load static %}
{% load utils %}

{% block title %}
  {% trans "Categories" context "Category list page title" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-scenes{% endblock %}

{% block menu_content_management_header_class %}active{% endblock %}
{% block menu_scene_class %}active{% endblock %}

{% block header_menu %}
  {{ block.super }}
{% endblock %}

{% block header_extra %}
{% if scene.pk %}
<a class="dropdown-button right" href="#" data-activates="scene-delete" data-constrainwidth="false">
  <svg data-src="{% static 'dashboard/images/more-vert.svg' %}" height="24" width="24" ></svg>
</a>
<ul id="scene-delete" class="dropdown-content">
  <li>
    <a class="modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:scene-delete' pk=scene.pk %}">
      {% trans "Remove scene" context "Voucher action" %}
    </a>
  </li>
</ul>
{% endif %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:scene-list' %}">
        {% trans "Banners" context "Dashboard scenes list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:scene-list' %}">
        <svg data-src="{% static 'dashboard/images/arrow-left.svg' %}" fill="#fff" width="20px" height="20px" ></svg>
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% if scene.pk %}
          {{ scene }}
        {% else %}
          {% trans "Agregar nuevo scene" context "Sale (discount) breadcrumbs" %}
        {% endif %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data" id="form-sales" novalidate>
          <div class="card-content card-content-form">
            {% csrf_token %}
            {% if form.non_field_errors %}
              <blockquote>
                {% for non_field_error in form.non_field_errors %}
                  {{ non_field_error }}
                {% endfor %}
              </blockquote>
            {% endif %}
            <div class="row">
              {{ form.name|materializecss }}
            </div>
            <div class="row">
              {{ form.image|materializecss }}
            </div>

            <span class="card-title">
              {% trans 'Publish' context 'slider form card title: public and default sub form' %}
            </span>

            <div class="row">
                {{ form.active_on|materializecss:"s12 m6" }}
                {{ form.active_until|materializecss:"s12 m6" }}
            </div>

            <div class="row">
              {{ form.is_active|materializecss:"pt-0 s12 m6" }}
            </div>
          </div>

          <div class="card-action right-align">
            <a href="{% url 'dashboard:scene-list' %}" class="btn-flat waves-effect">
              {% trans "Cancel" context "Dashboard cancel action" %}
            </a>
            {% if scene.pk %}
              <button type="submit" class="btn waves-effect">
                {% trans "Update" context "Dashboard update action" %}
              </button>
            {% else %}
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box"></div>
  </div>
{% endblock %}

templates/dashboard/widget/scene/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load mptt_tags %}
{% load materializecss %}
{% load static %}
{% load utils %}

{% block title %}
  {% trans "Categories" context "Category list page title" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-scenes{% endblock %}

{% block menu_content_management_header_class %}active{% endblock %}
{% block menu_scene_class %}active{% endblock %}

{% block header_menu %}
  {{ block.super }}
{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <a href="{% url 'dashboard:scene-create' %}" class="btn-fab-default waves-effect waves-light" title="{% trans 'Add category' context 'Category list add button text' %}">
      <svg data-src="{% static 'dashboard/images/add.svg' %}"></svg>
    </a>
  </div>
{% endblock %}



{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li class="visible-s">
      <span>
        {% trans "Scenes" context "Dashboard scenes list" %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="scenes row">
    <div class="col s12 l9">
      {% if scenes %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table data-table-description">
              <thead>
                <tr>
                  {% trans "Name" context "Category list table header name" as label %}
                  {% sorting_header 'name' label is_wide=True %}

                  <th>
                    {% trans "Active" context "Slider list table header is active" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for scene in scenes %}
                  <tr data-action-go="{% url 'dashboard:scene-details' pk=scene.pk %}">
                    <td>
                      {{ scene.name }}
                    </td>
                    <td class="nowrap" style="pointer-events:none;">
                      <input id="id_{{slider.pk}}_active" name="active" class="filled-in green" type="checkbox" {% if scene.is_active %}checked="checked"{% endif %}>
                      <label for="id_{{scene.pk}}_active"></label>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% paginate scenes %}
      {% else %}
        {% if is_empty %}
          {% include './zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No se encontraron baners." context "Empty category list message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    {% if not is_empty %}
    <div class="col s12 l3" id="filters">
      {% filters filter_set %}
    </div>
    {% endif %}
  </div>
{% endblock %}

templates/dashboard/widget/scene/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No scene found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  <p>
    {% blocktrans %}
      Scenes are engaging visual content, ideal to show our customers exciting news about our products.
    {% endblocktrans %}
  </p>
  <p>
    {% blocktrans %}
      You can create scenes by using the <span class="btn-fab-presentation"><svg data-src="{{ img_path }}"></svg></span> button.
    {% endblocktrans %}
  </p>
{% endblock %}